#!/bin/bash
# a simple utility to watch a file's size change over time
# (c) 2018 P Mansfield released under the GPL latest licence
#
# versions
# 20180919 - fixed EXPECTED logic
# 20180918 - used bash internal math not expr
# 20170810 - first version


if [ "$1" == "" -o "$1" == "-h" ] ; then
	echo "Usage: filegrow filename {expected}"
	echo "expected is the expected file size, in KB - optional"
	exit 0
fi

# default sleep 1 sec
PERIOD=1
if [ "$1" == "-i" ] ; then
	shift
	PERIOD=$1
	shift
fi

FILENAME="$1"
if [ ! -f "$FILENAME" ] ; then
	echo "Error, $FILENAME not found"
	exit 1
fi

if [ "$2" != "" ] ; then
	EXPECTED="$2"
else
	EXPECTED=0
fi

KB10=$(( 1024 * 10 ))
MB10=$(( 1024 * 1024 * 10 ))

OLD=-1
while [ 1 ] ; do
	if [ ! -f "$FILENAME" ] ; then
		printf "File has disappeared\n"
		exit 0
	fi
	NEW=`stat -c '%s' "$FILENAME"`
	DDD=`date +%H:%M:%S`
	sleep $PERIOD
	if [ $OLD -ne -1 ] ; then
		printf "Time: %8s  Size: %16d B,   " $DDD $NEW
		NEWKB=$(( $NEW / 1024 ))
		NEWMB=$(( $NEWKB / 1024 ))
		if [ "$NEWKB" -lt 4096 ] ; then
			printf "%10d KiB" $NEWKB
		else
			printf "%10d MiB" $NEWMB
		fi

		printf "; Growth: "
		DIFF=$(( $NEW - $OLD ))
		DIFFKBS=$(( DIFF   / 1024 / PERIOD ))
		DIFFMBS=$(( DIFFKB / 1024 / PERIOD ))

		if [ $DIFF -gt $KB10 ] ; then
			if [ $DIFF -gt $MB10 ] ; then
				printf "%8d MiB/s" $DIFFMBS
			else
				printf "%8d KiB/s" $DIFFKBS
			fi
		else
			printf "%8d B/s" $DIFF
		fi


		if [ "$EXPECTED" -gt 0 ] ; then
			LEFTKB=$(( $EXPECTED - $NEWKB ))
			printf "; Remainder: %4d KB" $LEFTKB

			if [ "$LEFTKB" -le 0 ] ; then
				printf "; Finish: already?"
			elif [ "$DIFFKBS" -eq 0 ] ; then
				printf "; Finish: never?"
			else
				DRTN=$(( $PERIOD * $LEFTKB / $DIFFKBS ))
				printf "; Finish: %d s" $DRTN
			fi
		fi

		printf "\n"
	fi
	OLD=$NEW
done


