#!/bin/bash
# a simple utility to watch a file's size change over time
# (c) 2018 P Mansfield released under the GPL latest licence
#
# versions
# 20180919 - fixed EXPECTED logic
# 20180918 - used bash internal math not expr
# 20170810 - first version


if [ "$1" == "" -o "$1" == "-h" ] ; then
	echo "Usage: filegrow filename {expected}"
	echo "expected is the expected file size, in KB - optional"
	exit 0
fi

# default sleep 1 sec
PERIOD=1
if [ "$1" == "-i" ] ; then
	shift
	PERIOD=$1
	shift
fi

FILENAME="$1"
if [ ! -f "$FILENAME" ] ; then
	echo "Error, $FILENAME not found"
	exit 1
fi

if [ "$2" != "" ] ; then
	EXPECTED="$2"
else
	EXPECTED=0
fi

KB10=$(( 1024 * 10 ))
MB10=$(( 1024 * 1024 * 10 ))

OLD=-1
while [ 1 ] ; do
	if [ ! -f "$FILENAME" ] ; then
		echo "File has disappeared"
		exit 0
	fi
	NEW=`stat -c '%s' "$FILENAME"`
	DDD=`date +%H:%M:%S`
	sleep $PERIOD
	if [ $OLD -ne -1 ] ; then
		echo -n "Time: $DDD	Size: $NEW B  "
		NEWKB=$(( $NEW / 1024 ))
		NEWMB=$(( $NEWKB / 1024 ))
		echo -n "$NEWMB  MiB	"

		echo -n "Growth: "
		DIFF=$(( $NEW - $OLD ))
		DIFFKB=$(( $DIFF / 1024 ))
		DIFFMB=$(( $DIFFKB / 1024 ))

		if [ $DIFF -gt $KB10 ] ; then
			if [ $DIFF -gt $MB10 ] ; then
				echo -n "$DIFFMB MiB	"
			else
				echo -n "$DIFFKB KiB	"
			fi
		else
			echo -n "$DIFF B	"
		fi


		if [ "$EXPECTED" -gt 0 ] ; then
			LEFTKB=$(( $EXPECTED - $NEWKB ))
			echo -n "Remainder: $LEFTKB KB	"

			if [ $DIFFKB -ne 0 -a $LEFTKB -ne 0 ] ; then
				DRTN=$(( $PERIOD * $LEFTKB / $DIFFKB ))
				echo -n "Finish: $DRTN s"
			fi
		fi

		echo ""
	fi
	OLD=$NEW
done


